name: rtorrent
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.2.5
  path_provider: ^2.0.5
  path: ^1.8.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lints: ^2.1.1

flutter:
  uses-material-design: true